// This file was auto-generated by prisma-generator-typescript-interfaces

export interface Experience {
  id: number;
  position: string;
  startDate: Date;
  endDate: Date | null;
  organization: string | null;
  description: string;
  createdDt: Date | null;
  updatedDt: Date | null;
  isDeleted: boolean;
  techs?: TechOnExperience[];
  tags?: TagOnExperience[];
}

export interface Project {
  id: number;
  title: string;
  date: Date;
  description: string;
  body: string;
  url: string | null;
  createdDt: Date | null;
  updatedDt: Date | null;
  isDeleted: boolean;
  imageId: number | null;
  image?: Image | null;
  techs?: TechOnProject[];
  tags?: TagOnProject[];
}

export interface Note {
  id: number;
  title: string;
  description: string;
  body: string;
  imageId: number | null;
  image?: Image | null;
  isDeleted: boolean;
  createdDt: Date | null;
  updatedDt: Date | null;
  techs?: TechOnNote[];
  tags?: TagOnNote[];
}

export interface Image {
  id: number;
  caption: string | null;
  fileName: string;
  createdDt: Date | null;
  Project?: Project[];
  Note?: Note[];
  Tech?: Tech[];
}

export interface Tech {
  id: number;
  name: string;
  order: number;
  imageId: number | null;
  image?: Image | null;
  TechOnExperience?: TechOnExperience[];
  TechOnProject?: TechOnProject[];
  TechOnNote?: TechOnNote[];
}

export interface TechOnExperience {
  id: number;
  Experience?: Experience;
  Tech?: Tech;
  ExperienceId: number;
  TechId: number;
}

export interface TechOnProject {
  id: number;
  Project?: Project;
  Tech?: Tech;
  ProjectId: number;
  TechId: number;
}

export interface TechOnNote {
  id: number;
  Note?: Note;
  Tech?: Tech;
  NoteId: number;
  TechId: number;
}

export interface Tag {
  id: number;
  name: string;
  TagOnExperience?: TagOnExperience[];
  TagOnProject?: TagOnProject[];
  TagOnNote?: TagOnNote[];
}

export interface TagOnExperience {
  id: number;
  Experience?: Experience;
  Tag?: Tag;
  ExperienceId: number;
  TagId: number;
}

export interface TagOnProject {
  id: number;
  Project?: Project;
  Tag?: Tag;
  ProjectId: number;
  TagId: number;
}

export interface TagOnNote {
  id: number;
  Note?: Note;
  Tag?: Tag;
  NoteId: number;
  TagId: number;
}
