// This file was auto-generated by prisma-generator-typescript-interfaces

export interface Experience {
  id: number;
  position: string;
  startDate: Date;
  endDate: Date | null;
  organization: string | null;
  description: string;
  createdDt: Date | null;
  updatedDt: Date | null;
  isDeleted: boolean;
  techs?: TechOnExperience[];
  tags?: TagOnExperience[];
}

export interface Project {
  id: number;
  title: string;
  date: Date;
  description: string;
  body: string;
  url: string | null;
  createdDt: Date | null;
  updatedDt: Date | null;
  isDeleted: boolean;
  imageId: number | null;
  image?: Image | null;
  techs?: TechOnProject[];
  tags?: TagOnProject[];
}

export interface Blog {
  id: number;
  title: string;
  description: string;
  body: string;
  imageId: number | null;
  image?: Image | null;
  isDeleted: boolean;
  createdDt: Date | null;
  updatedDt: Date | null;
  techs?: TechOnBlog[];
  tags?: TagOnBlog[];
}

export interface Image {
  id: number;
  caption: string | null;
  fileName: string;
  createdDt: Date | null;
  Project?: Project[];
  Blog?: Blog[];
}

export interface Tech {
  id: number;
  name: string;
  TechOnExperience?: TechOnExperience[];
  TechOnProject?: TechOnProject[];
  TechOnBlog?: TechOnBlog[];
}

export interface TechOnExperience {
  id: number;
  Experience?: Experience;
  Tech?: Tech;
  ExperienceId: number;
  TechId: number;
}

export interface TechOnProject {
  id: number;
  Project?: Project;
  Tech?: Tech;
  ProjectId: number;
  TechId: number;
}

export interface TechOnBlog {
  id: number;
  Blog?: Blog;
  Tech?: Tech;
  BlogId: number;
  TechId: number;
}

export interface Tag {
  id: number;
  name: string;
  TagOnExperience?: TagOnExperience[];
  TagOnProject?: TagOnProject[];
  TagOnBlog?: TagOnBlog[];
}

export interface TagOnExperience {
  id: number;
  Experience?: Experience;
  Tag?: Tag;
  ExperienceId: number;
  TagId: number;
}

export interface TagOnProject {
  id: number;
  Project?: Project;
  Tag?: Tag;
  ProjectId: number;
  TagId: number;
}

export interface TagOnBlog {
  id: number;
  Blog?: Blog;
  Tag?: Tag;
  BlogId: number;
  TagId: number;
}
